# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_name',
            field=models.CharField(default='NOUSER', max_length=20),
            preserve_default=False,
        ),
    ]
